Resources:
  PaymentRequestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.stage}-paymentRequest # name of the table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id # partition key
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1